# Generated by Django 4.2.1 on 2023-05-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=250)),
                ('contenu', models.CharField(max_length=250)),
                ('date_publication', models.DateField()),
                ('public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('symbole_boursier', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Associer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourse.article')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourse.entreprise')),
            ],
        ),
    ]
